### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 344880328** [SkyD666/Imomoe#101]
CrashInfo:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.skyd.imomoe/com.skyd.imomoe.view.activity.BackupRestoreActivity}: android.view.InflateException: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Error inflating class androidx.fragment.app.FragmentContainerView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3585)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3745)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2165)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8163)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.view.InflateException: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.s(SourceFile:7)
	at com.google.crypto.tink.proto.a.D(Unknown Source:2)
	at g6.a$a.b(SourceFile:2)
	at g6.a$a.a(Unknown Source:13)
	at com.skyd.imomoe.ext.v.b(SourceFile:12)
	at com.skyd.imomoe.view.fragment.WebDavFragment.h(SourceFile:6)
	at androidx.preference.PreferenceFragmentCompat.onCreate(SourceFile:2)
	at androidx.fragment.app.Fragment.performCreate(Unknown Source:26)
	at androidx.fragment.app.y.e(SourceFile:2)
	at androidx.fragment.app.y.k(SourceFile:7)
	at androidx.fragment.app.FragmentManager.C(SourceFile:15)
	at androidx.fragment.app.FragmentManager.Z(Unknown Source:91)
	at androidx.fragment.app.FragmentManager.B(Unknown Source:31)
	at androidx.fragment.app.FragmentContainerView.<init>(SourceFile:7)
	at androidx.fragment.app.s.onCreateView(Unknown Source:16)
	at androidx.fragment.app.FragmentActivity.onCreateView(SourceFile:4)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1071)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:999)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at com.skyd.imomoe.view.activity.BackupRestoreActivity.Q(SourceFile:2)
	at com.skyd.imomoe.view.activity.BaseActivity.onCreate(SourceFile:4)
	at com.skyd.imomoe.view.activity.BackupRestoreActivity.onCreate(Unknown Source:0)
	at android.app.Activity.performCreate(Activity.java:8247)
	at android.app.Activity.performCreate(Activity.java:8218)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3558)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3745)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2165)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8163)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
android.view.InflateException: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.s(SourceFile:7)
	at com.google.crypto.tink.proto.a.D(Unknown Source:2)
	at g6.a$a.b(SourceFile:2)
	at g6.a$a.a(Unknown Source:13)
	at com.skyd.imomoe.ext.v.b(SourceFile:12)
	at com.skyd.imomoe.view.fragment.WebDavFragment.h(SourceFile:6)
	at androidx.preference.PreferenceFragmentCompat.onCreate(SourceFile:2)
	at androidx.fragment.app.Fragment.performCreate(Unknown Source:26)
	at androidx.fragment.app.y.e(SourceFile:2)
	at androidx.fragment.app.y.k(SourceFile:7)
	at androidx.fragment.app.FragmentManager.C(SourceFile:15)
	at androidx.fragment.app.FragmentManager.Z(Unknown Source:91)
	at androidx.fragment.app.FragmentManager.B(Unknown Source:31)
	at androidx.fragment.app.FragmentContainerView.<init>(SourceFile:7)
	at androidx.fragment.app.s.onCreateView(Unknown Source:16)
	at androidx.fragment.app.FragmentActivity.onCreateView(SourceFile:4)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1071)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:999)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at com.skyd.imomoe.view.activity.BackupRestoreActivity.Q(SourceFile:2)
	at com.skyd.imomoe.view.activity.BaseActivity.onCreate(SourceFile:4)
	at com.skyd.imomoe.view.activity.BackupRestoreActivity.onCreate(Unknown Source:0)
	at android.app.Activity.performCreate(Activity.java:8247)
	at android.app.Activity.performCreate(Activity.java:8218)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActi

**Comment by SkyD666** [comment]
卸载重装或清除数据试试
