### ISSUE TITLE
1.7.0再次崩溃

### ISSUE THREAD

**Issue by tapttr** [SkyD666/Imomoe#103]
CrashInfo:
java.lang.IllegalStateException: Already resumed, but proposed with update CompletedExceptionally[java.lang.Exception: onGettingError,url:https://www.yhdmp.net/vp/22174-1-12.html,errorCode:2]
	at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(Unknown Source:12)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(Unknown Source:66)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(Unknown Source:7)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(Unknown Source:10)
	at com.skyd.imomoe.model.impls.custom.CustomPlayModel$getPlayData$2$1$1.onGettingError(CustomPlayModel.kt:133)
	at com.skyd.imomoe.util.html.source.web.GettingWebViewClient.onGettingError$lambda-6(Unknown Source:7)
	at com.skyd.imomoe.util.html.source.web.GettingWebViewClient.a(Unknown Source:0)
	at com.skyd.imomoe.util.html.source.web.d.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8254)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by SkyD666** [comment]
你从数据源商店升级数据源版本，就没问题了
