### ISSUE TITLE
。

### ISSUE THREAD

**Issue by GreatPowerStyle** [SkyD666/Imomoe#105]
CrashInfo:
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionf{f4bc position=4 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{c688949 VFED.V... ......ID 0,0-720,423 #7f0a04cc app:id/rv_search_activity}, adapter:c.b.a.a.a.m@ccd4a99, layout:androidx.recyclerview.widget.LinearLayoutManager@b79915e, context:com.skyd.imomoe.view.activity.SearchActivity@e8dd8f
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition()
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline()
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition()
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition()
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next()
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk()
	at androidx.recyclerview.widget.LinearLayoutManager.fill()
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren()
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1()
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout()
	at androidx.recyclerview.widget.RecyclerView.onLayout()
	at android.view.View.layout(View.java:16966)
	at android.view.ViewGroup.layout(ViewGroup.java:5604)
	at com.scwang.smart.refresh.layout.SmartRefreshLayout.onLayout(:4)
	at android.view.View.layout(View.java:16966)
	at android.view.ViewGroup.layout(ViewGroup.java:5604)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1206)
	at android.view.View.layout(View.java:16966)
	at android.view.ViewGroup.layout(ViewGroup.java:5604)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:398)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
	at android.view.View.layout(View.java:16966)
	at android.view.ViewGroup.layout(ViewGroup.java:5604)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2022)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1865)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1774)
	at android.view.View.layout(View.java:16966)
	at android.view.ViewGroup.layout(ViewGroup.java:5604)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:398)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
	at android.view.View.layout(View.java:16966)
	at android.view.ViewGroup.layout(ViewGroup.java:5604)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2022)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1865)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1774)
	at android.view.View.layout(View.java:16966)
	at android.view.ViewGroup.layout(ViewGroup.java:5604)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:398)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2820)
	at android.view.View.layout(View.java:16966)
	at android.view.ViewGroup.layout(ViewGroup.java:5604)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2635)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2329)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1367)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6974)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:922)
	at android.view.Choreographer.doCallbacks(Choreographer.java:724)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:908)
	at android.os.Handler.handleCallback(Handler.java:819)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:210)
	at android.app.ActivityThread.main(ActivityThread.java:5982)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)

**Comment by SkyD666** [comment]
什么版本的
