### ISSUE TITLE
电视投屏问题

### ISSUE THREAD

**Issue by Biyi-lab** [SkyD666/Imomoe#107]

**Comment by SkyD666** [comment]
用这个就好了
[app_release.zip](https://github.com/SkyD666/Imomoe/files/9139435/app_release.zip)

**Comment by Biyi-lab** [comment]
这个版本也不行，甚至会直接error，app crash掉。

**Comment by SkyD666** [comment]
有报错信息吗

**Comment by Biyi-lab** [comment]
晚上我给你发一下，当时没有截。

**Comment by Biyi-lab** [comment]
[CrashInfo:]
java.lang.IllegalArgumentException: Type of the key (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:e979f479-c98a-b504-5b85-431f18e2cd24, Descriptor: http://192.168.2.248:49152/description.xml, Root: true is not supported. On Android you can only use types which can be stored inside the Bundle.
 at androidx.compose.runtime.saveable.SaveableStateHolderImpl.b(Unknown Source:98)
 at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1.invoke(SourceFile:12)
 at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$createContentLambda$1.invoke(Unknown Source:8)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(Unknown Source:57)
 at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$2$1$1.invoke(SourceFile:2)
 at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$2$1$1.invoke(Unknown Source:8)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(Unknown Source:57)
 at androidx.compose.runtime.b.a(Unknown Source:22)
 at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(SourceFile:3)
 at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Unknown Source:0)
 at androidx.compose.runtime.m1.f(SourceFile:4)
 at androidx.compose.runtime.ComposerImpl.W(SourceFile:12)
 at androidx.compose.runtime.l.d(SourceFile:3)
 at androidx.compose.runtime.Recomposer.a(SourceFile:4)
 at androidx.compose.runtime.ComposerImpl$b.a(SourceFile:2)
 at androidx.compose.runtime.ComposerImpl$b.a(SourceFile:2)
 at androidx.compose.runtime.l.m(Unknown Source:15)
 at androidx.compose.ui.layout.v.e(SourceFile:18)
 at androidx.compose.ui.layout.v$b.v(SourceFile:11)
 at androidx.compose.foundation.lazy.layout.h.R(SourceFile:2)
 at androidx.compose.foundation.lazy.grid.w.a(Unknown Source:8)
 at androidx.compose.foundation.lazy.grid.LazyMeasuredLineProvider.a(SourceFile:12)
 at androidx.compose.foundation.lazy.grid.LazyGridKt$rememberLazyGridMeasurePolicy$1$1.invoke-0kLqBqw(SourceFile:22)
 at androidx.compose.foundation.lazy.grid.LazyGridKt$rememberLazyGridMeasurePolicy$1$1.invoke(SourceFile:2)
 at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$2$1.invoke-0kLqBqw(SourceFile:4)
 at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$2$1.invoke(SourceFile:2)
 at androidx.compose.ui.layout.w.a(SourceFile:17)
 at androidx.compose.ui.node.h.O(SourceFile:10)
 at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.q0(Unknown Source:10)
 at androidx.compose.ui.node.u.O(SourceFile:4)
 at androidx.compose.foundation.layout.FillModifier.q0(Unknown Source:110)
 at androidx.compose.ui.node.u.O(SourceFile:4)
 at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(SourceFile:2)
 at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(Unknown Source:0)
 at androidx.compose.runtime.snapshots.f$a.a(SourceFile:2)
 at androidx.compose.runtime.snapshots.SnapshotStateObserver.c(SourceFile:10)
 at androidx.compose.ui.node.OwnerSnapshotObserver.e(Unknown Source:17)
 at androidx.compose.ui.node.OwnerSnapshotObserver.d(SourceFile:2)
 at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.K0(SourceFile:23)
 at androidx.compose.ui.node.LayoutNode.O(SourceFile:4)
 at androidx.compose.ui.node.LayoutNode.P(SourceFile:5)
 at androidx.compose.ui.node.t.d(Unknown Source:7)
 at androidx.compose.ui.node.t.j(SourceFile:16)
 at androidx.compose.ui.node.t.h(SourceFile:4)
 at androidx.compose.ui.platform.AndroidComposeView.d(Unknown Source:15)
 at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:21)
 at android.view.View.draw(View.java:22002)
 at android.view.View.updateDisplayListIfDirty(View.java:20859)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
 at android.view.View.updateDisplayListIfDirty(View.java:20817)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
 at android.view.View.updateDisplayListIfDirty(View.java:20817)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
 at android.view.View.updateDisplayListIfDirty(View.java:20817)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
 at android.view.View.updateDisplayListIfDirty(View.java:20817)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
 at android.view.View.updateDisplayListIfDirty(View.java:20817)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4621)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4594)
 at android.view.View.updateDisplayListIfDirty(View.java:20817)
 at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:583)
 at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:589)
 at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
 at android.view.ViewRootImpl.draw(ViewRootImpl.java:4317)
 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4125)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3385)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
 at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
 at android.view.Choreographer.doFrame(Choreographer.java:911)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
 at android.os.Handler.handleCallback(Handler.java:900)
 at android.os.Handler.dispatchMessage(Handler.java:103)
 at android.os.Looper.loop(Looper.java:219)
 at android.app.ActivityThread.main(ActivityThread.java:8668)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by SkyD666** [comment]
[app_release.zip](https://github.com/SkyD666/Imomoe/files/9150314/app_release.zip)
这个解决了
