### ISSUE TITLE
点击数据源商店崩溃

### ISSUE THREAD

**Issue by mochen-six** [SkyD666/Imomoe#109]
CrashInfo:
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.skyd.imomoe/com.skyd.imomoe.view.activity.ConfigDataSourceActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2112)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1757)
	at android.app.Activity.startActivityForResult(Activity.java:4803)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivityForResult(Activity.java:4743)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivity(Activity.java:5164)
	at b1.a$a.b(Unknown Source:0)
	at androidx.fragment.app.Fragment.startActivity(SourceFile:2)
	at androidx.fragment.app.Fragment.startActivity(Unknown Source:1)
	at j4.i.a(Unknown Source:27)
	at androidx.preference.Preference.A(SourceFile:3)
	at androidx.preference.Preference$a.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:6663)
	at android.view.View.performClickInternal(View.java:6635)
	at android.view.View.access$3100(View.java:794)
	at android.view.View$PerformClick.run(View.java:26199)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by mochen-six** [comment]
问题相同，重复的issue。

**Comment by mochen-six** [comment]
版本1.7.1_Akarin

**Comment by SkyD666** [comment]
卸载重装软件，如果还不行的话，建议换个设备试试
