### ISSUE TITLE
点击设置里的自定义数据源后，弹出这些报错信息，把软件的数据清空后依然如此

### ISSUE THREAD

**Issue by lidawei97688** [SkyD666/Imomoe#29]
CrashInfo:
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.skyd.imomoe/com.skyd.imomoe.view.activity.ConfigDataSourceActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2112)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1757)
	at android.app.Activity.startActivityForResult(Activity.java:4789)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivityForResult(Activity.java:4729)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivity(Activity.java:5150)
	at android.app.Activity.startActivity(Activity.java:5118)
	at com.skyd.imomoe.view.activity.SettingActivity$a.onClick(java-style lambda group:31)
	at android.view.View.performClick(View.java:6653)
	at android.view.View.performClickInternal(View.java:6625)
	at android.view.View.access$3100(View.java:786)
	at android.view.View$PerformClick.run(View.java:26223)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7439)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by SkyD666** [comment]
安卓版本和手机型号是什么？

**Comment by lidawei97688** [comment]
华为mate20
安卓9.0.0

**Comment by lidawei97688** [comment]
顺便一提，刚装上那会还能打开来着，等回家开加速器下载好ads数据源想导入结果发现这app在打开方式里消失了，进设置的自定义数据源也是弹出报错

**Comment by SkyD666** [comment]
很奇怪的问题，目前不知道原因。你可以卸载重装app试试，或者换台手机看看有没有相似的问题。

**Comment by lidawei97688** [comment]
卸载重装后好了
