### ISSUE TITLE
手动导入数据源后崩溃

### ISSUE THREAD

**Issue by StephenSSR** [SkyD666/Imomoe#33]
`CrashInfo:
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	... 1 more
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.skyd.imomoe/files/DataSourceJar/CustomDataSource1.ads: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:575)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at c.g.a.e.w(Unknown Source:19)
	at c.g.a.e.z(:1)
	at c.b.a.a.a.h.h(:4)
	at androidx.recyclerview.widget.RecyclerView$Adapter.i(Unknown Source:0)
	at androidx.recyclerview.widget.RecyclerView$q.j(:71)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(:3)
	at androidx.recyclerview.widget.LinearLayoutManager.v1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.u0(:19)
	at androidx.recyclerview.widget.RecyclerView.s(:2)
	at androidx.recyclerview.widget.RecyclerView.q(:7)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:862)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3875)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3303)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2262)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1205)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1002)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:213)
	at android.view.Choreographer.doFrame(Choreographer.java:903)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1190)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8182)
	... 3 more
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8068)
	at libcore.io.IoBridge.open(IoBridge.java:561)
	... 60 more
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.skyd.imomoe/files/DataSourceJar/CustomDataSource1.ads: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:575)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at c.g.a.e.w(Unknown Source:19)
	at c.g.a.e.z(:1)
	at c.b.a.a.a.h.h(:4)
	at androidx.recyclerview.widget.RecyclerView$Adapter.i(Unknown Source:0)
	at androidx.recyclerview.widget.RecyclerView$q.j(:71)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(:3)
	at androidx.recyclerview.widget.LinearLayoutManager.v1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.u0(:19)
	at androidx.recyclerview.widget.RecyclerView.s(:2)
	at androidx.recyclerview.widget.RecyclerView.q(:7)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:862)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3875)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3303)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2262)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1205)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1002)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:213)
	at android.view.Choreographer.doFrame(Choreographer.java:903)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1190)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8182)
	... 3 more
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8068)
	at libcore.io.IoBridge.open(IoBridge.java:561)
	... 60 more
java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.skyd.imomoe/files/DataSourceJar/CustomDataSource1.ads: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:575)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at c.g.a.e.w(Unknown Source:19)
	at c.g.a.e.z(:1)
	at c.b.a.a.a.h.h(:4)
	at androidx.recyclerview.widget.RecyclerView$Adapter.i(Unknown Source:0)
	at androidx.recyclerview.widget.RecyclerView$q.j(:71)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(:3)
	at androidx.recyclerview.widget.LinearLayoutManager.v1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.u0(:19)
	at androidx.recyclerview.widget.RecyclerView.s(:2)
	at androidx.recyclerview.widget.RecyclerView.q(:7)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:862)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3875)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3303)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2262)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1205)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1002)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:213)
	at android.view.Choreographer.doFrame(Choreographer.java:903)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1190)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8182)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8068)
	at libcore.io.IoBridge.open(IoBridge.java:561)
	... 60 more
android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8068)
	at libcore.io.IoBridge.open(IoBridge.java:561)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at c.g.a.e.w(Unknown Source:19)
	at c.g.a.e.z(:1)
	at c.b.a.a.a.h.h(:4)
	at androidx.recyclerview.widget.RecyclerView$Adapter.i(Unknown Source:0)
	at androidx.recyclerview.widget.RecyclerView$q.j(:71)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(:3)
	at androidx.recyclerview.widget.LinearLayoutManager.v1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.u0(:19)
	at androidx.recyclerview.widget.RecyclerView.s(:2)
	at androidx.recyclerview.widget.RecyclerView.q(:7)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:862)
	at android.view.View.layout(View.java:23312)
	at android.view.ViewGroup.layout(ViewGroup.java:6489)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3875)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3303)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2262)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1205)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1002)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:213)
	at android.view.Choreographer.doFrame(Choreographer.java:903)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1190)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8182)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
`
设备一加9coloros12

**Comment by StephenSSR** [comment]
修改权限后正常了
