### ISSUE TITLE
崩溃报告

### ISSUE THREAD

**Issue by zhred** [SkyD666/Imomoe#41]
CrashInfo:
java.lang.IllegalArgumentException: Unexpected char 0x5047 at 31 in Referer value: https://www.yhdmp.net/s_all?kw=假面骑士&pagesize=24&pageindex=1
	at m.v$b.b()
	at m.v$a.a(:3)
	at i.p.h$a.a()
	at com.skyd.imomoe.util.coil.CoilUtil$loadImage$3.invoke(:4)
	at com.skyd.imomoe.util.coil.CoilUtil$loadImage$3.invoke()
	at com.skyd.imomoe.util.coil.CoilUtil.b(:5)
	at com.skyd.imomoe.util.coil.CoilUtil.a(:7)
	at com.skyd.imomoe.util.coil.CoilUtil.c()
	at c.b.a.a.a.l.h(:6)
	at androidx.recyclerview.widget.RecyclerView$Adapter.i()
	at androidx.recyclerview.widget.RecyclerView$q.j(:71)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(:3)
	at androidx.recyclerview.widget.LinearLayoutManager.v1()
	at androidx.recyclerview.widget.LinearLayoutManager.g1(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.B1()
	at androidx.recyclerview.widget.LinearLayoutManager.N0()
	at androidx.recyclerview.widget.RecyclerView.l0()
	at androidx.recyclerview.widget.RecyclerView.k0()
	at androidx.recyclerview.widget.RecyclerView.onTouchEvent(:2)
	at android.view.View.dispatchTouchEvent(View.java:9328)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2564)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2250)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2592)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at com.scwang.smart.refresh.layout.SmartRefreshLayout.dispatchTouchEvent()
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2570)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2452)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1749)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2927)
	at g.b.e.i.dispatchTouchEvent()
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2405)
	at android.view.View.dispatchPointerEvent(View.java:9548)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4518)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4316)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3826)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3886)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3845)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3993)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4050)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3826)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3886)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3845)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3826)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6242)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6216)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6177)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6349)
	at android.view.ViewRootImpl$ColorWindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7609)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:216)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:192)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6316)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6372)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:862)
	at android.view.Choreographer.doCallbacks(Choreographer.java:674)
	at android.view.Choreographer.doFrame(Choreographer.java:604)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:848)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)

**Comment by SkyD666** [comment]
请尝试1.3.0_Akarin版本
https://github.com/SkyD666/Imomoe/releases/tag/20
