### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 2511446597** [SkyD666/Imomoe#50]
CrashInfo:
java.io.FileNotFoundException: /storage/emulated/0/Download/CustomDataSource1.ads: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1475)
	at c.g.a.e.m(Unknown Source:20)
	at com.skyd.imomoe.view.activity.ConfigDataSourceActivity$importDataSource$$inlined$show$lambda$1$a.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7752)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 6 more
android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7752)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1475)
	at c.g.a.e.m(Unknown Source:20)
	at com.skyd.imomoe.view.activity.ConfigDataSourceActivity$importDataSource$$inlined$show$lambda$1$a.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:923)

**Comment by SkyD666** [comment]
允许存储权限即可

**Comment by SkyD666** [comment]
1.3.0_Akarin版本解决
https://github.com/SkyD666/Imomoe/releases/tag/20
