### ISSUE TITLE
secret.gradle does no exist

### ISSUE THREAD

**Issue by Tingday** [SkyD666/Imomoe#6]
Gradle project sync failed. 
请大神帮忙看一下怎么回事。

部分错误如下：
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:37)
	at org.gradle.api.Script$apply.callCurrent(Unknown Source)
	at build_2jzusv5uqz831ihdc7gozvtx0.run(.\Imomoe\app\build.gradle:9)

**Comment by SkyD666** [comment]
因为这个文件包括了一些敏感信息，例如apk签名密码等等，所以并没有放到github上。你可以尝试自己签名apk，然后将其他用到此文件内容的代码注释。

**Comment by Tingday** [comment]
还是没办法运行。删除相关代码以后依然出现更多错误。

**Comment by SkyD666** [comment]
> 还是没办法运行。删除相关代码以后依然出现更多错误。

截个图看看

**Comment by Tingday** [comment]
方便留个联系方式吗？我的邮件woyufan@163.com
