### ISSUE TITLE
最新的示例

### ISSUE THREAD

**Issue by lbwstco** [SkyD666/Imomoe#60]
`CrashInfo:
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V in class Lcom/skyd/imomoe/bean/TabBean; or its super classes (declaration of 'com.skyd.imomoe.bean.TabBean' appears in base.apk)
	at com.skyd.imomoe.model.impls.custom.CustomHomeModel.getAllTabData(CustomHomeModel.kt:20)
	at com.skyd.imomoe.model.impls.custom.CustomHomeModel$getAllTabData$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:9)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
`

**Comment by SkyD666** [comment]
在https://github.com/SkyD666/Imomoe/releases
这里下载相应版本的数据源，不同版本的可能不兼容
