### ISSUE TITLE
打开自定义数据源崩溃

### ISSUE THREAD

**Issue by arqueidist** [SkyD666/Imomoe#74]
CrashInfo:
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.skyd.imomoe/com.skyd.imomoe.view.activity.ConfigDataSourceActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2112)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1757)
	at android.app.Activity.startActivityForResult(Activity.java:4781)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivityForResult(Activity.java:4721)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivity(Activity.java:5142)
	at d0.a$a.b(Unknown Source:0)
	at androidx.fragment.app.Fragment.startActivity(:2)
	at androidx.fragment.app.Fragment.startActivity(Unknown Source:1)
	at m2.d.c(:1)
	at androidx.preference.Preference.y(:3)
	at androidx.preference.Preference$a.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:6652)
	at android.view.View.performClickInternal(View.java:6624)
	at android.view.View.access$3100(View.java:787)
	at android.view.View$PerformClick.run(View.java:26213)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7470)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by SkyD666** [comment]
什么型号的设备，安卓版本

**Comment by arqueidist** [comment]
> 什么型号的设备，安卓版本

安卓9，荣耀V10

**Comment by SkyD666** [comment]
很奇怪的问题，目前貌似只有华为手机安卓9出现过这个现象

**Comment by SkyD666** [comment]
[app_release_github_1.4.0_Akarin.zip](https://github.com/SkyD666/Imomoe/files/8397266/app_release_github_1.4.0_Akarin.zip)
你试试这个

**Comment by arqueidist** [comment]
> [app_release_github_1.4.0_Akarin.zip](https://github.com/SkyD666/Imomoe/files/8397266/app_release_github_1.4.0_Akarin.zip)
> 你试试这个

没问题了(｡￫v￩｡)

**Comment by SkyD666** [comment]
真的奇怪，玄学问题用玄学方式解决
