### ISSUE TITLE
软件崩溃

### ISSUE THREAD

**Issue by tapttr** [SkyD666/Imomoe#91]
CrashInfo:
java.lang.IllegalStateException: Already resumed, but proposed with update CompletedExceptionally[java.lang.Exception: onGettingError,url:https://m.yhdmp.net/vp/22174-1-9.html,errorCode:2]
	at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(Unknown Source:12)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(Unknown Source:66)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(Unknown Source:7)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(Unknown Source:10)
	at com.skyd.imomoe.model.impls.custom.CustomPlayModel$getPlayData$2$1$1.onGettingError(CustomPlayModel.kt:133)
	at com.skyd.imomoe.util.html.source.web.GettingWebViewClient.onGettingError$lambda-6(Unknown Source:7)
	at com.skyd.imomoe.util.html.source.web.GettingWebViewClient.a(Unknown Source:0)
	at com.skyd.imomoe.util.html.source.web.c.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by SkyD666** [comment]
能否复现？

**Comment by tapttr** [comment]
说实话我也不知道我操作了什么，就选集数的时候卡了，然后乱点了几下其他集，之后就崩了。

**Comment by SkyD666** [comment]
[app_release_github_1.7.0_Akarin.zip](https://github.com/SkyD666/Imomoe/files/8984157/app_release_github_1.7.0_Akarin.zip)
尝试这个版本，安装后一定要在数据源商店更新数据源2

**Comment by SkyD666** [comment]
1.7.0版本已解决
