### ISSUE TITLE
崩溃闪退 报错如下

### ISSUE THREAD

**Issue by qqyc** [SkyD666/Imomoe#92]
CrashInfo:
java.lang.IllegalStateException: Already resumed, but proposed with update CompletedExceptionally[java.lang.Exception: onGettingError,url:https://www.yhdmp.net/vp/152-1-53.html,errorCode:2]
	at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(Unknown Source:12)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(Unknown Source:66)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(Unknown Source:7)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(Unknown Source:10)
	at com.skyd.imomoe.model.impls.custom.CustomPlayModel$getPlayData$2$1$1.onGettingError(CustomPlayModel.kt:133)
	at com.skyd.imomoe.util.html.source.web.GettingWebViewClient.onGettingError$lambda-6(Unknown Source:7)
	at com.skyd.imomoe.util.html.source.web.GettingWebViewClient.a(Unknown Source:0)
	at com.skyd.imomoe.util.html.source.web.c.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by SkyD666** [comment]
能否复现？

**Comment by SkyD666** [comment]
https://github.com/SkyD666/Imomoe/issues/91#issuecomment-1166219988

**Comment by SkyD666** [comment]
1.7.0版本已解决
