### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by Oneyuanjoy** [SkyD666/Imomoe#95]
CrashInfo:
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
	at i8.b1.e(SourceFile:2)
	at i8.b1.d(SourceFile:12)
	at i8.b1.a(Unknown Source:65)
	at com.skyd.imomoe.view.adapter.variety.c.i(SourceFile:3)
	at androidx.recyclerview.widget.RecyclerView$r.j(SourceFile:81)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(SourceFile:3)
	at androidx.recyclerview.widget.LinearLayoutManager.e1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.R0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.h0(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView.s(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView.q(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
	at android.view.View.layout(View.java:23711)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at com.scwang.smart.refresh.layout.SmartRefreshLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:23711)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23711)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23711)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at androidx.recyclerview.widget.RecyclerView$k.S(Unknown Source:32)
	at androidx.recyclerview.widget.LinearLayoutManager.e1(SourceFile:14)
	at androidx.recyclerview.widget.LinearLayoutManager.R0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.h0(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView.s(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView.q(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
	at android.view.View.layout(View.java:23711)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at androidx.viewpager2.widget.ViewPager2.onLayout(Unknown Source:70)
	at android.view.View.layout(View.java:23711)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23711)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at d5.c.t(SourceFile:4)
	at d5.d.h(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:23711)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23711)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23711)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23711)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23711)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:868)
	at android.view.View.layout(View.java:23711)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4039)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3462)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2379)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9359)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1137)
	at android.view.Choreographer.doCallbacks(Choreographer.java:920)
	at android.view.Choreographer.doFrame(Choreographer.java:834)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1119)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:

**Comment by SkyD666** [comment]
能否复现

**Comment by SkyD666** [comment]
清除数据或卸载重装试试？

**Comment by SkyD666** [comment]
请尝试1.7.0_Akarin版本
