### ISSUE TITLE
打开数据源商店时崩溃。

### ISSUE THREAD

**Issue by 15354079449** [SkyD666/Imomoe#96]
CrashInfo:
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
	at i8.b1.e(SourceFile:2)
	at i8.b1.d(SourceFile:12)
	at i8.b1.a(Unknown Source:65)
	at com.skyd.imomoe.view.adapter.variety.c.i(SourceFile:3)
	at androidx.recyclerview.widget.RecyclerView$r.j(SourceFile:81)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(SourceFile:3)
	at androidx.recyclerview.widget.LinearLayoutManager.e1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.R0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.h0(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView.s(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView.q(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
	at android.view.View.layout(View.java:23559)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at com.scwang.smart.refresh.layout.SmartRefreshLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:23559)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23559)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23559)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.recyclerview.widget.RecyclerView$k.S(Unknown Source:32)
	at androidx.recyclerview.widget.LinearLayoutManager.e1(SourceFile:14)
	at androidx.recyclerview.widget.LinearLayoutManager.R0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.h0(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView.s(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView.q(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
	at android.view.View.layout(View.java:23559)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.viewpager2.widget.ViewPager2.onLayout(Unknown Source:70)
	at android.view.View.layout(View.java:23559)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23559)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at d5.c.t(SourceFile:4)
	at d5.d.h(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:23559)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23559)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23559)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23559)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23559)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:868)
	at android.view.View.layout(View.java:23559)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3898)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3348)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2309)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9084)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1158)
	at android.view.Choreographer.doCallbacks(Choreographer.java:948)
	at android.view.Choreographer.doFrame(Choreographer.java:877)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1140)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by SkyD666** [comment]
能否复现？

**Comment by SkyD666** [comment]
请尝试新版本1.7.0_Akarin
