### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by 116214MIX** [SkyD666/Imomoe#97]
CrashInfo:
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
	at i8.b1.e(SourceFile:2)
	at i8.b1.d(SourceFile:12)
	at i8.b1.a(Unknown Source:65)
	at com.skyd.imomoe.view.adapter.variety.c.i(SourceFile:3)
	at androidx.recyclerview.widget.RecyclerView$r.j(SourceFile:81)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(SourceFile:3)
	at androidx.recyclerview.widget.LinearLayoutManager.e1(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.R0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.h0(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView.s(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView.q(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
	at android.view.View.layout(View.java:23475)
	at android.view.ViewGroup.layout(ViewGroup.java:6559)
	at com.scwang.smart.refresh.layout.SmartRefreshLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:23475)
	at android.view.ViewGroup.layout(ViewGroup.java:6559)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23475)
	at android.view.ViewGroup.layout(ViewGroup.java:6559)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23475)
	at android.view.ViewGroup.layout(ViewGroup.java:6559)
	at androidx.recyclerview.widget.RecyclerView$k.S(Unknown Source:32)
	at androidx.recyclerview.widget.LinearLayoutManager.e1(SourceFile:14)
	at androidx.recyclerview.widget.LinearLayoutManager.R0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.h0(SourceFile:19)
	at androidx.recyclerview.widget.RecyclerView.s(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView.q(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
	at android.view.View.layout(View.java:23475)
	at android.view.ViewGroup.layout(ViewGroup.java:6559)
	at androidx.viewpager2.widget.ViewPager2.onLayout(Unknown Source:70)
	at android.view.View.layout(View.java:23475)
	at android.view.ViewGroup.layout(ViewGroup.java:6559)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23475)
	at android.view.ViewGroup.layout(ViewGroup.java:6559)
	at d5.c.t(SourceFile:4)
	at d5.d.h(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:4)
	at android.view.View.layout(View.java:23475)
	at android.view.ViewGroup.layout(ViewGroup.java:6559)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23475)
	at android.view.ViewGroup.layout(ViewGroup.java:6559)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23475)
	at android.view.ViewGroup.layout(ViewGroup.java:6559)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23475)
	at android.view.ViewGroup.layout(ViewGroup.java:6559)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23475)
	at android.view.ViewGroup.layout(ViewGroup.java:6559)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:873)
	at android.view.View.layout(View.java:23475)
	at android.view.ViewGroup.layout(ViewGroup.java:6559)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4056)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3456)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2369)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9332)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1185)
	at android.view.Choreographer.doCallbacks(Choreographer.java:975)
	at android.view.Choreographer.doFrame(Choreographer.java:875)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1170)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:

**Comment by SkyD666** [comment]
https://github.com/MaybeQHL/my_danmu_pub/files/8986991/app_release_github_1.7.0_Akarin.zip
试试这个

**Comment by SkyD666** [comment]
请尝试1.7.0_Akarin版本
