### ISSUE TITLE
点击备份与恢复应用崩溃

### ISSUE THREAD

**Issue by Garuda8D** [SkyD666/Imomoe#98]
CrashInfo:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.skyd.imomoe/com.skyd.imomoe.view.activity.BackupRestoreActivity}: android.view.InflateException: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Error inflating class androidx.fragment.app.FragmentContainerView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.view.InflateException: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.s(SourceFile:7)
	at com.google.crypto.tink.proto.a.D(Unknown Source:2)
	at g6.a$a.b(SourceFile:2)
	at g6.a$a.a(Unknown Source:13)
	at com.skyd.imomoe.ext.v.b(SourceFile:12)
	at com.skyd.imomoe.view.fragment.WebDavFragment.h(SourceFile:6)
	at androidx.preference.PreferenceFragmentCompat.onCreate(SourceFile:2)
	at androidx.fragment.app.Fragment.performCreate(Unknown Source:26)
	at androidx.fragment.app.y.e(SourceFile:2)
	at androidx.fragment.app.y.k(SourceFile:7)
	at androidx.fragment.app.FragmentManager.C(SourceFile:15)
	at androidx.fragment.app.FragmentManager.Z(Unknown Source:91)
	at androidx.fragment.app.FragmentManager.B(Unknown Source:31)
	at androidx.fragment.app.FragmentContainerView.<init>(SourceFile:7)
	at androidx.fragment.app.s.onCreateView(Unknown Source:16)
	at androidx.fragment.app.FragmentActivity.onCreateView(SourceFile:4)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.skyd.imomoe.view.activity.BackupRestoreActivity.Q(SourceFile:2)
	at com.skyd.imomoe.view.activity.BaseActivity.onCreate(SourceFile:4)
	at com.skyd.imomoe.view.activity.BackupRestoreActivity.onCreate(Unknown Source:0)
	at android.app.Activity.performCreate(Activity.java:7906)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
android.view.InflateException: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.s(SourceFile:7)
	at com.google.crypto.tink.proto.a.D(Unknown Source:2)
	at g6.a$a.b(SourceFile:2)
	at g6.a$a.a(Unknown Source:13)
	at com.skyd.imomoe.ext.v.b(SourceFile:12)
	at com.skyd.imomoe.view.fragment.WebDavFragment.h(SourceFile:6)
	at androidx.preference.PreferenceFragmentCompat.onCreate(SourceFile:2)
	at androidx.fragment.app.Fragment.performCreate(Unknown Source:26)
	at androidx.fragment.app.y.e(SourceFile:2)
	at androidx.fragment.app.y.k(SourceFile:7)
	at androidx.fragment.app.FragmentManager.C(SourceFile:15)
	at androidx.fragment.app.FragmentManager.Z(Unknown Source:91)
	at androidx.fragment.app.FragmentManager.B(Unknown Source:31)
	at androidx.fragment.app.FragmentContainerView.<init>(SourceFile:7)
	at androidx.fragment.app.s.onCreateView(Unknown Source:16)
	at androidx.fragment.app.FragmentActivity.onCreateView(SourceFile:4)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.skyd.imomoe.view.activity.BackupRestoreActivity.Q(SourceFile:2)
	at com.skyd.imomoe.view.activity.BaseActivity.onCreate(SourceFile:4)
	at com.skyd.imomoe.view.activity.BackupRestoreActivity.onCreate(Unknown Source:0)
	at android.app.Activity.performCreate(Activity.java:7906)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
android.view.InflateException: Binary XML file line #24 in com.skyd.imomoe:layout/activity_backup_restore: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.s(SourceFile:7)
	at com.google.crypto.tink.proto.a.D(Unknown Source:2)
	at g6.a$a.b(SourceFile:2)
	at g6.a$a.a(Unknown Source:13)
	at com.skyd.imomoe.ext.v.b(SourceFile:12)
	at com.skyd.imomoe.view.fragment.WebDavFragment.h(SourceFile:6)
	at androidx.preference.PreferenceFragmentCompat.onCreate(SourceFile:2)
	at androidx.fragment.app.Fragment.performCreate(Unknown Source:26)
	at androidx.fragment.app.y.e(SourceFile:2)
	at androidx.fragment.app.y.k(SourceFile:7)
	at androidx.fragment.app.FragmentManager.C(SourceFile:15)
	at androidx.fragment.app.FragmentManager.Z(Unknown Source:91)
	at androidx.fragment.app.FragmentManager.B(Unknown Source:31)
	at androidx.fragment.app.FragmentContainerView.<init>(SourceFile:7)
	at androidx.fragment.app.s.onCreateView(Unknown Source:16)
	at androidx.fragment.app.FragmentActivity.onCreateView(SourceFile:4)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.skyd.imomoe.view.activity.BackupRestoreActivity.Q(SourceFile:2)
	at com.skyd.imomoe.view.activity.BaseActivity.onCreate(SourceFile:4)
	at com.skyd.imomoe.view.activity.BackupRestoreActivity.onCreate(Unknown Source:0)
	at android.app.Activity.performCreate(Activity.java:7906)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.s(SourceFile:7)
	at com.google.crypto.tink.proto.a.D(Unknown Source:2)
	at g6.a$a.b(SourceFile:2)
	at g6.a$a.a(Unknown Source:13)
	at com.skyd.imomoe.ext.v.b(SourceFile:12)
	at com.skyd.imomoe.view.fragment.WebDavFragment.h(SourceFile:6)
	at androidx.preference.PreferenceFragmentCompat.onCreate(SourceFile:2)
	at androidx.fragment.app.Fragment.performCreate(Unknown Source:26)
	at androidx.fragment.app.y.e(SourceFile:2)
	at androidx.fragment.app.y.k(SourceFile:7)
	at androidx.fragment.app.FragmentManager.C(SourceFile:15)
	at androidx.fragment.app.FragmentManager.Z(Unknown Source:91)
	at androidx.fragment.app.FragmentManager.B(Unknown Source:31)
	at androidx.fragment.app.FragmentContainerView.<init>(SourceFile:7)
	at androidx.fragment.app.s.onCreateView(Unknown Source:16)
	at androidx.fragment.app.FragmentActivity.onCreateView(SourceFile:4)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.skyd.imomoe.view.activity.BackupRestoreActivity.Q(SourceFile:2)
	at com.skyd.imomoe.view.activity.BaseActivity.onCreate(SourceFile:4)
	at com.skyd.imomoe.view.activity.BackupRestoreActivity.onCreate(Unknown Source:0)
	at android.app.Activity.performCreate(Activity.java:7906)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
![Screenshot_2022-06-28-09-45-41-020_com skyd imomoe](https://user-images.githubusercontent.com/62003913/176069246-2b24971e-974c-4a35-ba67-e6217ff7a6fe.jpg)

**Comment by Garuda8D** [comment]
100%复现

**Comment by SkyD666** [comment]
清除数据或卸载重装试试

**Comment by Garuda8D** [comment]
果然
这样就没问题啦
感谢!

**Comment by SkyD666** [comment]
遇到这个奇怪的问题前，APP使用了多长时间了？

**Comment by Garuda8D** [comment]
有一段时间没打开了（大概两个月多一点）
今天打开在应用内更新，然后提示数据源也要更新，更新之后再打开就出现这个情况了

**Comment by SkyD666** [comment]
不知道原因，我感觉跟厂商定制的手机系统有关（备份和恢复功能在支持后基本上没更改过代码）

**Comment by Garuda8D** [comment]
嗯嗯
有可能
我这个手机刚刚刷了一个系统的官改包
可能是这个原因造成的
清楚数据之后重启就ok了
