### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by 8880880** [SkyD666/Imomoe#99]
CrashInfo:
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getFlags()' on a null object reference
	at android.app.ContextImpl.startActivity(ContextImpl.java:1083)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1064)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:411)
	at com.skyd.imomoe.util.Util.restartApp(Unknown Source:31)
	at com.skyd.imomoe.viewmodel.h.e(Unknown Source:20)
	at com.skyd.imomoe.view.activity.ConfigDataSourceActivity$setDataSource$2.invoke(SourceFile:2)
	at com.skyd.imomoe.view.activity.ConfigDataSourceActivity$setDataSource$2.invoke(Unknown Source:8)
	at com.skyd.imomoe.ext.l.onClick(Unknown Source:11)
	at androidx.appcompat.app.AlertController$c.handleMessage(Unknown Source:37)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by SkyD666** [comment]
清除数据或重装app试试
